### PR TITLE
refactor: revamp install to use fisher

### PR DESCRIPTION
**Pull request by edouard-lopez**
I automated the fetching of the binary and follow fish convention for completions so we can use [fisher](https://github.com/jorgebucaran/fisher)
Once it approved, we need to update the location of the plugin:

```diff
-fisher install edouard-lopez/pnpm-shell-completion
+fisher install g-plane/pnpm-shell-completion
```

### CODE REVIEW

**Comment by g-plane** [comment]
Where the `fisher` command comes from?

**Comment by edouard-lopez** [comment]
[Fisher](https://github.com/jorgebucaran/fisher) is the most popular plugin manager for fish ecosytem, I added a link to the repo. Also updated the source repo to install from, so it will work once merged.

**Comment by g-plane** [comment]
Considering fisher is not bulti in Fish, I think we should keep the original installation method but we can still add this new method.

**Comment by edouard-lopez** [comment]
Done

**Review by g-plane — APPROVED** [review]

**Pull request merged**
