### PR TITLE
perf: skipping gitignore files when traverse workspace.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
This is my computer info
```
  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 315.63 MB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
```

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
for project https://github.com/web-infra-dev/rspack
If I run ` time TARGET_PKG=@rspack/core FEATURE=scripts pnpm-shell-completion`, this is the result: 
```
prepare
build
dev
test
precompile-schema

________________________________________________________
Executed in  909.71 millis    fish           external
   usr time  157.10 millis  128.00 micros  156.97 millis
   sys time  762.42 millis  933.00 micros  761.49 millis
```
here is the profile 
image

**Comment by IWANABETHATGUY** [comment]
performance: 
**before**
```
prepare
build
dev
test
precompile-schema

________________________________________________________
Executed in  909.71 millis    fish           external
   usr time  157.10 millis  128.00 micros  156.97 millis
   sys time  762.42 millis  933.00 micros  761.49 millis
```

**after**

```
precompile-schema
build
prepare
test
dev

________________________________________________________
Executed in  164.30 millis    fish           external
   usr time   39.68 millis  101.00 micros   39.58 millis
   sys time  130.44 millis  689.00 micros  129.75 millis
```
huge win

**Comment by IWANABETHATGUY** [comment]
Another reason we could do this is: almost no one has a scenario like having a package belonging to a workspace but being ignored by `.gitignore`

**Comment by IWANABETHATGUY** [comment]
I have tested it locally, the function works fine with this modification.

**Review by g-plane — APPROVED** [review]
Thanks!

**Pull request merged**
